# Generated by Django 3.0 on 2020-01-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newprojecctapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('product_cost', models.IntegerField()),
                ('product_color', models.CharField(max_length=100)),
                ('cust_name', models.CharField(max_length=100)),
                ('cust_mobile', models.BigIntegerField()),
            ],
        ),
    ]
