# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-08 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newprojecctapp', '0002_homedata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='homedata',
            new_name='createdata',
        ),
    ]
