# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-01-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newprojecctapp', '0003_auto_20200108_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdata',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='product_image'),
        ),
    ]
